-d C:\Users\CCTV\Documents\C1_2025\Electronica Digital\LAB\Pracica 3\Fpga\Parqueo_project\impl\gwsynthesis\Parqueo_project.vg
-p GW5A-25B-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst C:\Users\CCTV\Documents\C1_2025\Electronica Digital\LAB\Pracica 3\Fpga\Parqueo_project\src\Parqueo_project.cst
-cfg C:\Users\CCTV\Documents\C1_2025\Electronica Digital\LAB\Pracica 3\Fpga\Parqueo_project\impl\pnr\device.cfg
-sdc C:\Users\CCTV\Documents\C1_2025\Electronica Digital\LAB\Pracica 3\Fpga\Parqueo_project\src\Parqueo_project.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
